### ISSUE TITLE
Need a contributors component

### ISSUE THREAD

**Issue by adavijit** [adavijit/BlogMan#100]
Need a contributors component which will fetch all details from GitHub API .

You can get the Contributors.jsx file inside the front-end folder. Make any changes there

Needs to show total PRs raised, commits, profile-photo, username and Full name

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue @adavijit .

**Comment by adavijit** [comment]
@ashishnagpal2498  go ahead

**Comment by ashishnagpal2498** [comment]
Okay , working on it.

**Comment by ashishnagpal2498** [comment]
Hi, @adavijit is there any wireframe design for this page so that I can work according to that ?

**Comment by simranaggarwal1999** [comment]
@adavijit Can I work upon this issue?

**Comment by adavijit** [comment]
No, just show list of contributors with their profile name,link, username,photo

**Comment by adavijit** [comment]
@simranaggarwal1999  go ahead and try to complete within tomorrow

**Comment by simranaggarwal1999** [comment]
@adavijit Sure

**Comment by simranaggarwal1999** [comment]
Kindly assign it to me

**Comment by ashishnagpal2498** [comment]
I am working on it.

**Comment by adavijit** [comment]
@ashishnagpal2498  send your PR too.

**Comment by ashishnagpal2498** [comment]
Sure , Thank you

**Comment by simranaggarwal1999** [comment]
@adavijit Kindly review my pull request.
