### ISSUE TITLE
Sending a welcome email to users on successful signup

### ISSUE THREAD

**Issue by lakshyajit165** [adavijit/BlogMan#115]
It is nice to send users who are registering on blogman, a welcome email, as seen in most sites/apps. 
@rajatmw1999. I would like to work on this issue.

**Comment by rajatmw1999** [comment]
Assigned to @lakshyajit165

**Comment by Major2001** [comment]
I would like to work on this issue

**Comment by gpsuhas20** [comment]
@lakshyajit165  i would like to work on this issue

**Comment by hitha2000** [comment]
@lakshyajit165  i would like to work on this issue
