### ISSUE TITLE
Need improvement in Contribution.md file

### ISSUE THREAD

**Issue by adavijit** [adavijit/BlogMan#127]
Improve Contribution.md file with the steps to follow for contributing.

1. It should have how to start the front-end server.
2. It should have how to start the backend server with database part.

Happy Coding. 👍

**Comment by adad20** [comment]
@adavijit  I wanna take this.

**Comment by adavijit** [comment]
@adad20 go ahead

**Comment by shreyakapoor08** [comment]
I want to work on this issue.

**Comment by Chetanjain10** [comment]
Please assign me this issue. I want to work on this.
