### ISSUE TITLE
Code the wireframe for landing blog page

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#137]
Code the wireframe for the landing page of BlogMan. The landing page's wireframe is stored at "\front-end\public\wire-frame\Blog Page.png".
Be sure to make the design responsive for mobile as well.

**Comment by BhuwanChandra** [comment]
@rajatmw1999 I would like to work on this issue.

**Comment by rajatmw1999** [comment]
assigned to @BhuwanChandra . Submit it by 20th March.

**Comment by BhuwanChandra** [comment]
@rajatmw1999 do I need to create the upper navbar also or the lower part only?

![Blog Page](https://user-images.githubusercontent.com/46065877/76826233-f329fe80-6841-11ea-85e5-44cb83ecf78b.png)
