### ISSUE TITLE
Code the wireframe for QNA section

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#140]
The wireframe for QNA section is stored at "\front-end\public\wire-frame\QnA Section.png".
Be sure to make the design responsive for mobile as well. This is just the header of the education section of blogman.

**Comment by Satyam3976** [comment]
I am a GSSOC 2020 participant. Please assign it to me so that I can start working on this.

**Comment by arpita-in** [comment]
Please assign it to me @rajatmw1999  and further guide me to proceed for the same.

**Comment by Satyam3976** [comment]
@adavijit Please assign this task to me.Currently I have no issue to work upon.Thanks:)

**Comment by shreyakapoor08** [comment]
@rajatmw1999 hey can i work on this?

**Comment by RiaJha02** [comment]
Hello, I would like to try this! Please assign this task to me.
Thanks!

**Comment by adavijit** [comment]
@RiaJha02  go ahead

**Comment by RiaJha02** [comment]
Sure, Thanks!

**Comment by RiaJha02** [comment]
@rajatmw1999 I have completed the required code, please review it.
Thank you!
