### ISSUE TITLE
Code the wireframe for ourTeam section

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#142]
The wireframe for education section is stored at "\front-end\public\wire-frame\Our team.png".
Be sure to make the design responsive for mobile as well. This is just the header of the education section of blogman.

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by Satyam3976** [comment]
I am a GSSOC 2020 participant. Please assign it to me so that I can work on it asap.

**Comment by rajatmw1999** [comment]
assigned to @Satyam3976 . Submit it by 20th March.

**Comment by Satyam3976** [comment]
@adavijit @rajatmw1999 @PrathamDogra Please review my PR.
