### ISSUE TITLE
Code the wireframe for MCQ QUIZ section

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#143]
The wireframe for MCQ section is stored at "\front-end\public\wire-frame\Quiz MCQ section .png".
Be sure to make the design responsive for mobile as well. This is just the header of the education section of blogman.

**Comment by lakshyajit165** [comment]
@rajatmw1999 I would like to work on this issue.

**Comment by rajatmw1999** [comment]
Assigned to @lakshyajit165 .
