### ISSUE TITLE
Code the wireframe for MCQ NUMERICAL section

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#144]
The wireframe for NUMERICAL QUIZ section is stored at "\front-end\public\wire-frame\Quiz NUMERICAL section.png".
Be sure to make the design responsive for mobile as well. This is just the header of the education section of blogman.

**Comment by shreyakapoor08** [comment]
can I work on this?

**Comment by guptavarun619** [comment]
May I work on this issue. I'm a bit familiar with material-ui library used in this project.

**Comment by shwhite17** [comment]
can I work on this issue, sir? @adavijit
