### ISSUE TITLE
Code the wireframe for SUBJECTIVE QUIZ section

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#145]
The wireframe for SUBJECTIVE QUIZ section is stored at "\front-end\public\wire-frame\Quiz_Subjective .png".
Be sure to make the design responsive for mobile as well. This is just the header of the education section of blogman.

**Comment by shreyakapoor08** [comment]
Can I take this up?

**Comment by rajatmw1999** [comment]
assigned to @shreyakapoor08 . Submit it by 20th March.
