### ISSUE TITLE
Names of Mentors in README.md

### ISSUE THREAD

**Issue by utkzas** [adavijit/BlogMan#152]
Name of Ayushi (M) is not written in the README.md file. Please allow me to add it

**Comment by utkzas** [comment]
please label it as gssoc20 also

**Comment by Kuljeet-123** [comment]
@utkzas I'm a GSSOC'20 participant .I would like to work on this.Please assign me this.

**Comment by utkzas** [comment]
@PrathamDogra The issue was resolved in PR #156 / PR #157 and was merged to master branch successfully.
