### ISSUE TITLE
The npm recommender package is showing error while installation.

### ISSUE THREAD

**Issue by PrathamDogra** [adavijit/BlogMan#154]
The recommender which is used in back-end/src/routes/api/blog.js is showing error while installation
![recommender](https://user-images.githubusercontent.com/43649218/76704292-ffa53e80-66fd-11ea-8361-c14a0644d78d.png)

I recommend to use something else for the recommendation algorithm.

**Comment by PrathamDogra** [comment]
The issue is in compliance with PR #129

**Comment by imabp** [comment]
Use Good Enough Recommendation package: `npm i ger`
in `back-end/src/routes/api/blog.js` 

I actually researched on this. 
But to be honest, this would be my first time, to implement this. I am super excited to learn something new.

**Comment by imabp** [comment]
@PrathamDogra @rajatmw1999 @adavijit  I have fixed the issue with a new module content-based-recommender. Please review pull #174

**Comment by imabp** [comment]
@PrathamDogra  @adavijit @rajatmw1999  Please close the issue, as it has been resolved.
