### ISSUE TITLE
Adding a Markdown Article Writer for Blog

### ISSUE THREAD

**Issue by imabp** [adavijit/BlogMan#155]
On discussion over slack with @rajatmw1999  , we decided to add this feature. 
I have already made this in my profile here is the link: [github](https://github.com/imabp/Markdown_Blog)

**Comment by imabp** [comment]
@rajatmw1999 pls assign this to me.

**Comment by shwhite17** [comment]
@rajatmw1999 pls assign this to me.

**Comment by imabp** [comment]
I have already made it earlier based on our talk on slack .[Here is the link ](https://github.com/imabp/Markdown_Blog)

**Comment by imabp** [comment]
Sir, I have made a pull request: #170 on this issue, it also includes, the video description about the article writer I have created.

**Comment by imabp** [comment]
I have already put the stuff into New Ideas folder, as it is a new one.
Here is the quick video of Markdown Article Writer
[Watch it on YouTube](https://www.youtube.com/watch?v=XX29zqwBylM&feature=youtu.be)

**Comment by imabp** [comment]
Thank you for merging the PR #170
