### ISSUE TITLE
Fix minor error in Contrbution.md file

### ISSUE THREAD

**Issue by Satyam3976** [adavijit/BlogMan#160]
In the contribution.md file, there is a minor typo in which the git command written to pull from the upstream repository is incorrect.

**Comment by Satyam3976** [comment]
I am a GSSOC 2020 participant. Please assign it to me so that I can work on it.

**Comment by Valdermaut** [comment]
can I work on it

**Comment by adavijit** [comment]
@Valdermaut  Go ahead

**Comment by Satyam3976** [comment]
@adavijit Sir, I had already fix this issue on my local machine. and waiting for mentors to assign me so that I can send pull request to you. I had already fixed my last issue and waiting for my next issue that why I opened this issue
so please assign me.

**Comment by adavijit** [comment]
@Satyam3976  please mention your PR here

**Comment by Satyam3976** [comment]
https://github.com/adavijit/BlogMan/pull/169
@adavijit
