### ISSUE TITLE
Logo for Project Blogman

### ISSUE THREAD

**Issue by utkzas** [adavijit/BlogMan#164]
As we can see, many projects of GSSoC have Logo. Although a logos primary purpose is to identity, they can also be leveraged to communicate important brand messages and values.

Hence, there is a need of Logo for Project Blogman.

**Comment by shwhite17** [comment]
assign it to me, please?

**Comment by shwhite17** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/57324656/77370117-2d395a00-6d86-11ea-990f-fce3e250fff1.png)
above is logo for the app ^_^

**Comment by shwhite17** [comment]
we can also add  "Publish your words in your way! Whether you'd like to share your knowledge, experiences or the latest news, publish your own articles in a unique and smart way"  this quote to logo

**Comment by shwhite17** [comment]
assign it to me........

**Comment by RiaJha02** [comment]
Hello, I would like to take this task up! 
Thank you!
