### ISSUE TITLE
The backend dosen't throw error if MongoDB connection fails

### ISSUE THREAD

**Issue by irshadjsr21** [adavijit/BlogMan#17]
The `mongoose.connect` function in `backend/server.js` is not being checked for errors.

**Comment by rajatmw1999** [comment]
This issue has been assigned to irshadjsr21.

**Comment by vipuldcoder** [comment]
I am interested with issue.

**Comment by rajatmw1999** [comment]
> I am interested with the issue.

Its already assigned. You can checkout other issues as well.
