### ISSUE TITLE
The frontend has incorrect API url

### ISSUE THREAD

**Issue by irshadjsr21** [adavijit/BlogMan#18]
While the backend port was changed to `5000`, the frontend is still making API requests to port `3000`

**Comment by guptavarun619** [comment]
If they ought to run on same PORT ```5000``` i could change it for front-end from ```3000``` to ```5000```.

**Comment by irshadjsr21** [comment]
Let's see what the mentors have to say.

**Comment by vipuldcoder** [comment]
I am Interested

**Comment by Major2001** [comment]
i am interested in this issue

**Comment by LMPerera** [comment]
I would like to work on this issue
