### ISSUE TITLE
To check if an email used for registering an user is valid.

### ISSUE THREAD

**Issue by lakshyajit165** [adavijit/BlogMan#183]
It's a way to prevent users from entering any random emails while registering themselves on the webapp. It could be done through an API called apilayer. It checks the authenticity of an email through an API call.

@PrathamDogra, I would like to work on this issue. Please assign it to me.

**Comment by ishukhanchi** [comment]
I would like to work on this issue. Can you please assign it to me.

**Comment by Aakansha99** [comment]
Kindly assign this issue to me
