### ISSUE TITLE
Browser History Retreival

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#184]
Search and bring out APIs and npm packages or inbuilt browser javascript functions that retrieve the complete history of the current browser of the user. Also, find the same things for retrieving cookies and bookmarks of that particular browser.

The package should not only retrieve the history of the currently open tab like "window.history" does. It should retrieve the complete past history of the browser.

**Comment by rajatmw1999** [comment]
Make a notepad file and mention the packages or api links in that file and push that file.

**Comment by shreyakapoor08** [comment]
Can I work on it @rajatmw1999

**Comment by ashishnagpal2498** [comment]
Hi @rajatmw1999 , can I work on this issue?

**Comment by rajatmw1999** [comment]
@ashishnagpal2498 please submit the issue by tomorrow

**Comment by ashishnagpal2498** [comment]
Yes , I am working @rajatmw1999 .
