### ISSUE TITLE
InfoGraphics packages

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#185]
Search through the net and bring out the best info graphics package which is free.

It should include the functions of making browser renderable graphs and charts. Like bargraphs, pie charts etc.

We will use it to map the number of user visits and their activity while they are using the website.

Make a notepad file and mention the link of the package or API and push that file.

**Comment by shreyakapoor08** [comment]
Can I work on this ?

**Comment by irshadjsr21** [comment]
I think chart.js will do our work.

**Comment by rajatmw1999** [comment]
@shreyakapoor08 please submit the issue by tomorrow
