### ISSUE TITLE
MongoDB connection issue (gssoc 20)

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#19]
Participants are getting error messages and not able to connect to the mongoDB server. Fix the issue. Also add local as well as an online cluster connection. As of now, just let the statement with the local connection work and comment out the connection to the online cluster.
Whoever who will take up this issue is supposed to:

1. Create an online cluster with their personal account on MongoDB.
2. Connect with the BlogMan project.
3. Comment out the connection of the cluster and as of now, just let the application connect with the MongoDB on the local machine.

**Comment by Schitiz** [comment]
I would take it!!

**Comment by vipuldcoder** [comment]
I am interested with the issue. Needed Mentorship.

**Comment by rajatmw1999** [comment]
@vipuldcoder 
Issue is already assigned to @Schitiz . If he fails to solve it, i will reassign it o you.

**Comment by rajatmw1999** [comment]
Solved.
