### ISSUE TITLE
Traffic Dashboard

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#192]
Create a dashboard that displays the number of times a user has visited a website. Make use of infographic like piecharts or bar graphs and make the dashboard really easy to navigate and understand.

It include
1. Data of how many times user visited a website.
2. Total amount of time user stayed at website everytime they opened it.
3. Categorize the users interest in different fields like education, sports etc. take some dummy data for this,that is, consider you have the data history of user, now make a dashboard infographic to easily display users interest field and their engagement in different topics.

No need of any coding. Just upload wireframe for the above mentioned dashboard.

**Comment by Satyam3976** [comment]
Can I work on this? Please assign me @rajatmw1999

**Comment by FrozenGirl-spd** [comment]
Can i work on the same...

**Comment by rajatmw1999** [comment]
@FrozenGirl-spd sure
