### ISSUE TITLE
Database model for user activity

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#196]
Make a database model for saving the user activity on the website. 
The database model will consist of

1. IP address of the users network
2. Array of routes they visited on our site
3. Total time they spent on the website
4. Array of ids of posts they liked
5. Number of times this ip address visited the website.

**Comment by irshadjsr21** [comment]
I'd like to work on this.

**Comment by MsShandilya** [comment]
interested in this
