### ISSUE TITLE
Improving the Login and Signup Page using Material UI

### ISSUE THREAD

**Issue by lakshyajit165** [adavijit/BlogMan#20]
React Ant Design has a vivid collection of components, even more than angular material. It also has notification components (like the ones which show success/error message on completion or failure). I think it would be good to implement all the components using Ant Design as the official docs make them quite easy to implement

**Comment by vipuldcoder** [comment]
I am interested with the issue. Needed Mentorship towards making and impactful pull request.

**Comment by lakshyajit165** [comment]
I have created a pull request regarding this. I edited the issue heading because of the issue with Ant Design as discussed over slack

**Comment by Shreya-Gupta02** [comment]
interested
