### ISSUE TITLE
Update Readme to contain instructions to run the app on docker

### ISSUE THREAD

**Issue by lakshyajit165** [adavijit/BlogMan#201]
I would like to update the main readme file in the root of the project to contain instructions to run the entire app on docker. In this way, a person doesn't need to start the backend and frontend separately. I can write details(not too verbose ofcourse) instructions on how to do it.
@PrathamDogra and @rajatmw1999 Please assign this issue to me.

**Comment by PrathamDogra** [comment]
Go for it.
