### ISSUE TITLE
Prepare wireframe for Blog Page.

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#23]
BlogMan is all about blogging. Create a wireframe for a blog page which will have all the basic features of a blog. The topic, content, comments, likes, etc of a article. Try to make it minimilistic and simple.

**Comment by Swarnimashukla** [comment]
Hi @rajatmw1999  I would like to contribute to this issue . please assign it to me .

**Comment by rajatmw1999** [comment]
Issue assigned to @Swarnimashukla .

**Comment by guptavarun619** [comment]
Will it be okay if i collaborate with @Swarnimashukla on this one. I've got a few ideas for it. (P.S. is it important to use specific tools for creating wireframe?)

**Comment by rajatmw1999** [comment]
@guptavarun619 you can work with @Swarnimashukla on this issue . No limitations on tools, although XD is preferred.

**Comment by rajatmw1999** [comment]
Done.
