### ISSUE TITLE
Make API calls to Udemy API

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#25]
udemy.com provides API to fetch the data of particular courses based on a search query parameter. 
Make UDEMY API calls in the back end based on different search criterias like domain(web dev, data science), stack(mern mean, flutter etc) and authors. 
Fetch the JSON data and display it.

**Comment by irshadjsr21** [comment]
I'd like to take this up.

**Comment by rajatmw1999** [comment]
Issue assigned to @irshadjsr21

**Comment by adityasanil** [comment]
Can I work on this?

**Comment by rajatmw1999** [comment]
@adityasanil i suggest you start looking for issues not assigned to anyone. This is already assigned.
