### ISSUE TITLE
Implement Login/SignUP using Github account

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#27]
When a new user visits the website, he/she should be able to login using their github account. Implement the functionality along with a dummy login/signup page.

**Comment by adad20** [comment]
@rajatmw1999  I wanna take this along with google login/signup

**Comment by rajatmw1999** [comment]
Issue #27 assigned to @adad20

**Comment by simranaggarwal1999** [comment]
@rajatmw1999 I am interested to work upon this issue.

**Comment by LMPerera** [comment]
I would like to work on this issue

**Comment by BhuwanChandra** [comment]
@rajatmw1999 I would also like to work on this issue

**Comment by gpsuhas20** [comment]
i am interested to work on this issue
