### ISSUE TITLE
Implement Login/SignUP using Google account

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#28]
When a new user visits the website, he/she should be able to login using their github account. Implement the functionality along with a dummy login/signup page.

**Comment by adad20** [comment]
@rajatmw1999  I want to work on this issue

**Comment by rajatmw1999** [comment]
Issue assigned to @adad20

**Comment by Ramesh-geek** [comment]
I am also interested to work on this.

**Comment by DineshGowd** [comment]
I am willing to solve this issue 😊.

**Comment by LMPerera** [comment]
I would like to work on this issue

**Comment by Ramesh-geek** [comment]
When i will assignd i am waiting for the task to handle

**Comment by rajatmw1999** [comment]
It is already assigned to @adad20

**Comment by gpsuhas20** [comment]
i would like to work on this issue.
