### ISSUE TITLE
Create USERS model in MongoDB

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#29]
Create a mongoDB model for the users using the course comparison and blog website.
It should include the following fields :
1. Name
2. Email
3. Interests
4. Posts liked
5. Comments
6. Skills
7. College
8. Search interests

**Comment by Major2001** [comment]
I would like to work on this issue

**Comment by Endowmissy** [comment]
I am interested in working on this issue

**Comment by LMPerera** [comment]
I would like to work on this issue

**Comment by rajatmw1999** [comment]
@Major2001 have a look at the new issue #40. You also need to change that. Comment there that you are interested.
