### ISSUE TITLE
Create wireframe for a USER profile

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#30]
Create a simple and easy to use wireframe for a user profile. Like a instagram or facebook profile, it should have all links and details of users. A user profile for a user on Linkedin should be a good example of what is expected.

**Comment by lakshyajit165** [comment]
I am interested to work on this issue. Please assign it to me.

**Comment by aryasoni98** [comment]
I am interested to work on this issue . Please assign it to me

**Comment by guptavarun619** [comment]
I would like to contribute on this wire-frame. We can collaborate and come up with some good design which is user-friendly and serves the purpose.

**Comment by rajatmw1999** [comment]
@guptavarun619 you can connect with these people on slack to work on this issue

**Comment by rajatmw1999** [comment]
@aryasoni98 @lakshyajit165 Any updates on the issue??

**Comment by TheDudeThatCode** [comment]
@rajatmw1999 I also want to contribute to this please, do you expect something like this ?

https://images.app.goo.gl/75FSwt2g8r2Tp7ma8

@aryasoni98 @lakshyajit165 let's discuss it together.

**Comment by rajatmw1999** [comment]
@TheDudeThatCode two people are already assigned to the issue. I suggest you look out for some new issues

**Comment by guptavarun619** [comment]
@rajatmw1999 I've sent you a mock-up on slack. Please have a look and share your feedback.

**Comment by rajatmw1999** [comment]
@guptavarun619 This issue was not assigned to you.

**Comment by guptavarun619** [comment]
@rajatmw1999 You told me to "connect with these people on slack to work on this issue". Accordingly i initiated the discussion and came up with my idea for the issue.

**Comment by rajatmw1999** [comment]
Okay. My bad. Just say my comment. I will look into it. Did all of you guys work together for the wireframe you have sent me on slack?

**Comment by guptavarun619** [comment]
> Okay. My bad. Just say my comment. I will look into it. Did all of you guys work together for the wireframe you have sent me on slack?

Not exactly, actually before sending anything to you. I discussed it with fellow contributors for suggestions/ ideas and after all that i asked for you feedback so that i deliver according to what's expected. (If you just take a look and share your feedback, it'll benefit me to work according to expectation)

**Comment by rajatmw1999** [comment]
@guptavarun619 I have reviewed the wireframes and told you about the further proceedings.
