### ISSUE TITLE
Recommendation  algorithm

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#31]
Create a recommendation algorithm to recommend a user about new posts and new courses available  based on their previous history of interests, likes, comments and their skills. The new suggested posts are supposed to be present in the database and the users history and their previous likes are also supposed to be stored in DB.

**Comment by adad20** [comment]
@rajatmw1999 Can we use npm package for this?
If yes then I want to work on it.

**Comment by rajatmw1999** [comment]
Yes you can. I want the recommendations to be really helpful and realistic. Based on users history. You can use npm.

**Comment by simranaggarwal1999** [comment]
I am interested

**Comment by adad20** [comment]
@simranaggarwal1999  there is an npm package called recommender that is used to build the recommendation system that you may refer if you wanna use existing package.

**Comment by rajatmw1999** [comment]
@simranaggarwal1999  and @adad20  you guys can work together on this issue. Connect if you want on the slack DM.

**Comment by rajatmw1999** [comment]
@simranaggarwal1999 @adad20 what is the progress? also let me know about the npm package you are using for this task.

**Comment by adad20** [comment]
@rajatmw1999 We are using recommender and since @simranaggarwal1999 exams were going on we recently started.

**Comment by rajatmw1999** [comment]
Give me a date when you can finish. Also i am waiting for google/github auth from ur side @adad20

**Comment by adad20** [comment]
@rajatmw1999 Yes I will finish that by Tuesday. Actually a lil busy with college fest so I got late

**Comment by simranaggarwal1999** [comment]
@adad20 Aditya you also please have a look at the PR and make the required changes
