### ISSUE TITLE
Create a blog post model in MongoDB

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#32]
Create a model in mongodb for blog posts.
It should include
1. TOpic
2. content
3. author
4. topic
5. tags
6. likes
7. comments
8. source

**Comment by Major2001** [comment]
I would like to work on this issue

**Comment by Samarjiit** [comment]
i would like to work on this issue too

**Comment by LMPerera** [comment]
I would like to work on this issue

**Comment by BhuwanChandra** [comment]
@rajatmw1999 I would like to work on this issue, assign it to me.

**Comment by Schitiz** [comment]
I would like to take this issue.
