### ISSUE TITLE
Create UI Design BlogMan Application

### ISSUE THREAD

**Issue by aryasoni98** [adavijit/BlogMan#33]
I will create ui design for blogman application using XD .

**Comment by nitin1kumar1** [comment]
I am also quite comfortable with XD, can I be assigned this task.

**Comment by anushreejain98** [comment]
I am also interested to take up UI design

**Comment by JoshuaPoddoku** [comment]
Hello @aryasoni98 I would alspolike to do UI design

**Comment by JoshuaPoddoku** [comment]
Hello @rajatmw1999  I would also like to do UI design
