### ISSUE TITLE
After signing up Log In page should be opened.

### ISSUE THREAD

**Issue by PrathamDogra** [adavijit/BlogMan#39]
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

### Current Behaviour:

After a user registers, he gets directly logged in to the home page.
![Login](https://user-images.githubusercontent.com/43649218/75622786-1f027e80-5bca-11ea-93d4-77b0d2832738.gif)

### Expected Behaviour:

After the user registers he/she should see the login page.
![login](https://user-images.githubusercontent.com/43649218/75622801-448f8800-5bca-11ea-9a9f-5b7ad9f5bae3.png)

**Comment by irshadjsr21** [comment]
I don't think this is a bug. This is an approach almost every website use now.
The user has already entered the username and password while signup so it is not a good user experience to make the user type the same thing again for login.

Google, twitter, facebook and etc use the same approach.

**Comment by BhuwanChandra** [comment]
@PrathamDogra I would like to work on this issue, assign this to me.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by bhavesh0206s** [comment]
I would like to work on this issue

**Comment by rajatmw1999** [comment]
Assigned to @BhuwanChandra . Have a look at the Readme file. On the top you will find a link to marvelapp. We need the login and signup flow to be like that. Also,, refer to this issue created by @PrathamDogra
