### ISSUE TITLE
Change routes and front end according to new user model

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#40]
As per the new user model, also change the route and front end code to suit the new model in mongodb.

**Comment by irshadjsr21** [comment]
I'll take this up.

**Comment by rajatmw1999** [comment]
@irshadjsr21 Have a look at the PR #37 . Check the new model there and update the routes and front end accordingly. I am not merging pr #37   as of now. Once your work in this issue is done. I will merge both together.

**Comment by PrathamDogra** [comment]
@irshadjsr21 you have to change tow things. 
1. First, change the routes in router.post("/register") for the new body element which you have added in the model.
2. Change that in frontend components for the UI.

**Comment by rajatmw1999** [comment]
@irshadjsr21 The new UI and the new user model both are merged. You can work on this now. Any changes you think have to be done, do it. Also, while registerting, dont keep anything "required" except for essential things like password etc.

**Comment by irshadjsr21** [comment]
On it.
