### ISSUE TITLE
Create wireframes for QnA section.

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#46]
A QnA section like that of Stackoverflow has to be made in the website. Create a simple and easy to use wireframe. 
1. Add question
2. Add topic tags to question
3. Give answer
4. Like answer
5. Leave comment
6. Other similar question
7. People interested in question
8. Anything else you need to add according to you.

This wireframe should show all the questions and a short answer(100 words only) to each question. 

A separate wireframe will be created dedicated to one question through another question.

**Comment by guptavarun619** [comment]
The requirements provided are more than enough to work upon. Shall i get started with this?

**Comment by rajatmw1999** [comment]
Sure. Assigned. You have been assigned a number of issues. Make sure you don't delay the PRs.
