### ISSUE TITLE
Create wireframe for a particular question and its answer

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#47]
In the QnA section, when a user clicks on a particular question, he will be directed to a page dedicated particulary to that question and all its answers till date. create a simple and easy to use wireframe.

1. Add question
2. Add topic tags to question
3. Give answer
4. Like answer
5. Leave comment
6. Other similar question
7. People interested in question

Also add anything you think are needed to be added.

**Comment by taran1515** [comment]
@rajatmw1999 I am ready to work on this issue.

**Comment by rajatmw1999** [comment]
Assigned.
