### ISSUE TITLE
Compile a dark theme for BlogMan

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#49]
The blogman website is not completed yet. Before its completion, a dark theme needs to be ready to apply to it. 
Make use of your own dummy page and name it as "dark_theme.html".
Include, text, image, icons, emojis etc to it and give it a really cool dark theme.
This page will later on be used to add the dark theme to the complete website.
Create a separate CSS file and a separate folder for this theme.

Along with front-end and back-end, make a folder dark-theme and include the css and html file there before commiting.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by anmolkaur18** [comment]
Please assign this issue to me .I am interested in contributing to this

**Comment by SachindraFernando** [comment]
Can I work on this please

**Comment by Shreya-Gupta02** [comment]
interested

**Comment by rajatmw1999** [comment]
Assigned to @anmolkaur18

**Comment by rajatmw1999** [comment]
@SachindraFernando @Shreya-Gupta02 i am creating two more issues with the same problem. You can work on them.

**Comment by SachindraFernando** [comment]
@rajatmw1999  yeah sure

**Comment by Shreya-Gupta02** [comment]
> @SachindraFernando @Shreya-Gupta02 i am creating two more issues with the same problem. You can work on them.

yeah sure

**Comment by anmolkaur18** [comment]
@rajatmw1999 can we also use javascript?

**Comment by rajatmw1999** [comment]
Try to keep it to css and html only. Because it will only lead to integration problems. Why do you need JS anyways?

**Comment by anmolkaur18** [comment]
JS for toggling between light and dark theme

**Comment by anmolkaur18** [comment]
is toggling necessary?

**Comment by rajatmw1999** [comment]
If you are toggling, then you can use JS. It will be a nice feature.. go ahead with js
