### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#50]
Read through the issues that have been created until now and update the readme file with the new features that are being added to the blogMan. Specify the features that blogMan has. read the features from issues.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by rajatmw1999** [comment]
@vipuldcoder Assigned. Complete and put the PR by 4th March.

**Comment by Basilleaf24** [comment]
@rajatmw1999 Please assign me this issue,
I haven't been assigned any issues, I would like to contribute to this

**Comment by rajatmw1999** [comment]
Assigned to @Basilleaf24

**Comment by Basilleaf24** [comment]
@rajatmw1999 Thanks I'm working on it
