### ISSUE TITLE
Create wireframe for quiz section - MCQ

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#51]
BlogMan will have a quiz section where various types of questions will be asked like mcqs, subjective, numericals etc. 

Create wireframe for MCQ questions.

**Comment by shreyakapoor08** [comment]
rajatmw1999 I want to work on this issue

**Comment by rajatmw1999** [comment]
Go ahead @shreyakapoor08 . Make use of either Figma or XD. Most people are working on either of these.

**Comment by shreyakapoor08** [comment]
I am sorry @rajatmw1999  I thought we have to code in html,css in this issue. I don't have prior knowledge with designing using figma or XD

**Comment by rajatmw1999** [comment]
No problem. This is just wireframing for this page. Once the frames are complete, another issue for coding it with html, css with be opened. You can work on that.

**Comment by Swarnimashukla** [comment]
@rajatmw1999  i would like to take this issue .please assign it to me .

**Comment by rajatmw1999** [comment]
assigned to @Swarnimashukla . Submit by 5th march.

**Comment by Swarnimashukla** [comment]
hi @rajatmw1999  please review my pr #68  .
