### ISSUE TITLE
Create wireframe for quiz section - NUMERICAL

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#52]
BlogMan will have a quiz section where various types of questions will be asked like mcqs, subjective, numericals etc. 

Create wireframe for NUMERICALS questions.

**Comment by guptavarun619** [comment]
I would like work on this issue for GSSoC'20.

**Comment by rajatmw1999** [comment]
@guptavarun619 . Questions will be displayed and the user just needs to write either  a number or a string in the text box as answer. It will be one word. Either one number or one word. Assigned.

**Comment by guptavarun619** [comment]
Sounds pretty generic. I'll come up with some idea and share it on slack with you for your feedback?

**Comment by rajatmw1999** [comment]
Sure.
