### ISSUE TITLE
Create wireframe for quiz section - SUBJECTIVE

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#53]
BlogMan will have a quiz section where various types of questions will be asked like mcqs, subjective, numericals etc.

Create wireframe for SUBJECTIVE questions.

**Comment by Ankita1811** [comment]
@rajatmw1999 Can you please assign me to this?

**Comment by guptavarun619** [comment]
I would like work on this issue for GSSoC'20.

**Comment by rajatmw1999** [comment]
Assigned to @Ankita1811 .
