### ISSUE TITLE
Ideas Suggestion

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#54]
For those of you, not into coding too much. Here is an issue.

Come up with new, exciting, and innovative ideas for a Blog and Education website like BlogMan.
Let your imagination run wild and far away.

You can do research on internet, search through similar sites etc.
We want innovative ideas.

Create a separate folder in the main code along with backend and frontend folder. Name it "New_Ideas" and put your ideas in a text file in that folder.

**Comment by Aju100** [comment]
@rajatmw1999  can u assigned me this

**Comment by dipanshuraz** [comment]
@rajatmw1999  I am interested

**Comment by Ankita1811** [comment]
@rajatmw1999 I am interested. Can you assign me to this

**Comment by shreyakapoor08** [comment]
rajatmw1999 I want to work on this

**Comment by rajatmw1999** [comment]
This issue needs ideas not a particular code. So, i am assigning it to more than one people. @Aju100 @dipanshuraz @shreyakapoor08 . Properly read the way you need to commit. And come up with good and new ideas.

**Comment by shreyakapoor08** [comment]
sure

**Comment by rajatmw1999** [comment]
@dipanshuraz @shreyakapoor08 @Aju100 Submit your individual PRs and not in just one PR.

**Comment by Aju100** [comment]
sure

**Comment by AishwaryaVarma** [comment]
assign this to me

**Comment by rajatmw1999** [comment]
@dipanshuraz @Aju100 @shreyakapoor08 I want your ideas by tomorrow. Make sure to put the PR before 6th March.

**Comment by dipanshuraz** [comment]
ok @rajatmw1999

**Comment by rajatmw1999** [comment]
@dipanshuraz @Aju100 @shreyakapoor08  you need to put the pr today.

**Comment by rajatmw1999** [comment]
This issue will be reassigned today. So, put your PR before 12.

**Comment by Aju100** [comment]
i will put PR today.
