### ISSUE TITLE
Create wireframe for Our Team section.

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#56]
BlogMan will have a Our Team section displaying the name, pic, role and a small description of the team behind blogman.
Create a simple and easy to navigate wireframe for that.

**Comment by Ankita1811** [comment]
@rajatmw1999  Can I work on this please?

**Comment by guptavarun619** [comment]
I would like work on this issue for GSSoC'20.

**Comment by rajatmw1999** [comment]
Assigned to @Ankita1811  . Keep me posted in the slack channel. Also, i suggest either you use Figma or XD.
