### ISSUE TITLE
Create wireframe for books suggestions.

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#57]
BlogMan is all about sharing knowledge. It will have a books suggestions section.

Create a simple wireframe for this page.. it will display:

1. a list of books
2. name of book, author, pic, stars, genre, small description.
3. add to favorite button for every book in list.
4. anything that comes to your mind and you think is needed on this page can be added.

**Comment by Rukmini-Meda** [comment]
Interested to work on this issue. Experienced in XD and planning to use the same. Please assign this to me as part of GSSoC'20

**Comment by guptavarun619** [comment]
I would like work on this issue for GSSoC'20.

**Comment by rajatmw1999** [comment]
Assigned to @guptavarun619 . Keep me posted in the slack channel.

**Comment by anushreejain98** [comment]
@rajatmw1999 I am also interested in this task, could you please assign me this task in collab with @guptavarun619
