### ISSUE TITLE
Create wireframe for a particular book

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#58]
BlogMan is all about sharing knowledge. It will have a books suggestions section.

Create a simple wireframe for the page dedicated to a particular book.. it will display:

name of book, author, pic, stars, genre, description.
add to favorite button for book
anything that comes to your mind and you think is needed on this page can be added.

**Comment by Rukmini-Meda** [comment]
Hello, I am interested to work on this issue. I have experience with Adobe XD and Balsamiq. Please assign this to me. I will work on this issue using XD.

**Comment by guptavarun619** [comment]
I would like to work on this issue. Please assign me this.

**Comment by rajatmw1999** [comment]
Assigned to @Rukmini-Meda . Keep me posted in the slack channel about your progress.
