### ISSUE TITLE
User model error

### ISSUE THREAD

**Issue by irshadjsr21** [adavijit/BlogMan#61]
While resolving the issue #29, the PR #60 introduced the following line in the users model.

https://github.com/adavijit/BlogMan/blob/219e9986418390c44e5c2987de254db5e0921acb/back-end/src/models/User.js#L12

Which leads to the following error.

![Screenshot from 2020-03-02 20-50-21](https://user-images.githubusercontent.com/40335357/75690372-bbab4600-5cc8-11ea-99d8-c867667d6b31.png)

The `index` should be set to `true`.

**Comment by rajatmw1999** [comment]
@irshadjsr21 Would you like to take up this issue? Also, i think major2001 has a PR with conflicts.

**Comment by irshadjsr21** [comment]
Yea, I'll fix it.

**Comment by rajatmw1999** [comment]
Assigned to @irshadjsr21 . I suggest you put the PR today itself. So other dont have problem carrying forward.

**Comment by Endowmissy** [comment]
The reason why it was set to false is that,from the documentation,I learnt that,setting index to true is not good for production,only good for development,mayb the unique should have been removed
@irshadjsr21 let me know if you still want to take it up or I correct it here

**Comment by adityasanil** [comment]
Can I take up this issue?
