### ISSUE TITLE
Unable to register a new user. 

### ISSUE THREAD

**Issue by adityasanil** [adavijit/BlogMan#65]
``
![Screenshot 2020-03-03 at 02 06 23](https://user-images.githubusercontent.com/25709147/75715555-9aac1a80-5cf3-11ea-9ada-60d469e0ccd1.png)

I would like to fix this and refactor the auth module a bit.

**Comment by rajatmw1999** [comment]
Make a pull of the updated code and try again. It will work

**Comment by rajatmw1999** [comment]
Assigned . Fix it asap.

**Comment by rajatmw1999** [comment]
Issue #40 will solve it

**Comment by adityasanil** [comment]
The issue still exists.
