### ISSUE TITLE
Design and create a user profile component

### ISSUE THREAD

**Issue by adavijit** [adavijit/BlogMan#7]
**Design and create a user profile component inside the front-end folder using React**

**Directions**
1. User profile picture, name and details should be there
2. User's profile picture changing functionality should be there
3. Refer the screenshot below

![twitter_profile_card](https://user-images.githubusercontent.com/29899278/66889785-513b8700-f001-11e9-8c4f-63a7cc7e04b8.png)

> Attach a screenshot while sending a PR

**Comment by robertbegna** [comment]
hey i'd like to try this

**Comment by adavijit** [comment]
@robertbegna  go ahead!

**Comment by ashima20** [comment]
Hi is this done ? 
can i work on this?

**Comment by nitin1kumar1** [comment]
can I take this task?

**Comment by huonggiangbui** [comment]
I am interested. Can I solve this @adavijit ?

**Comment by rajatmw1999** [comment]
Closed
