### ISSUE TITLE
BlogMan dark theme 3

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#72]
The blogman website is not completed yet. Before its completion, a dark theme needs to be ready to apply to it.
Make use of your own dummy page and name it as "dark_theme_3.html".

Include, text, image, icons, emojis etc to it and give it a really cool dark theme.
This page will later on be used to add the dark theme to the complete website.
Create a separate CSS file and a separate folder for this theme.

Along with front-end and back-end, make a folder dark-theme and include the css and html file there before commiting.

**Comment by SachindraFernando** [comment]
I'm interested to work on this

**Comment by rajatmw1999** [comment]
@SachindraFernando assigned
