### ISSUE TITLE
Error while doing npm install in the back-end.

### ISSUE THREAD

**Issue by adad20** [adavijit/BlogMan#77]
Error is due to the minor mistake in the package-lock.json file in the back-end.
![Screenshot (75)](https://user-images.githubusercontent.com/55142272/75839704-73d30e80-5def-11ea-8de5-e7e669e54668.png)

Just add '}' in the last of the file and then do npm install.

**Comment by irshadjsr21** [comment]
@adad20 Are you working on this?
If you have solved this then please add a PR so that everyone can get the change.

**Comment by rajatmw1999** [comment]
@irshadjsr21 please put a pr for this issue asap.

**Comment by rajatmw1999** [comment]
@adad20 i will assign some other issue to you in replacement to this. This needs to be solved asap. Can't wait for your reply.

**Comment by adad20** [comment]
> @adad20 i will assign some other issue to you in replacement to this. This needs to be solved asap. Can't wait for your reply.

Okay I don't have any problem. Issue must be resolved quickly. I will work for another issue.

**Comment by irshadjsr21** [comment]
@adad20 checkout issue #80
