### ISSUE TITLE
Design and create a user post component

### ISSUE THREAD

**Issue by adavijit** [adavijit/BlogMan#8]
**Design and create a user post component**

**

> Refer this screenshot

**

![fa087966305da8b146f43f9cfefb2e29](https://user-images.githubusercontent.com/29899278/66850087-b78ac000-ef95-11e9-8bee-a9993015c185.jpg)

**Comment by theparselmouth** [comment]
Do you mean the CSS ?

**Comment by adavijit** [comment]
@theparselmouth  
you need to create a React component something like the screenshot I've mentioned before.
Obviously you need to use CSS and you may use another library or framework too.
Happy coding :)

**Comment by guptavarun619** [comment]
Shall i give it a try, i might be able to mimic the component screenshot provided. And as project already used material-ui component selection won't ambiguous. (Though i might need help in routing)

**Comment by adavijit** [comment]
Yes, go ahead! send a screenshot while sending pr

**Comment by RiaJha02** [comment]
Hey!! I would like to try this. May I?

**Comment by vipuldcoder** [comment]
Hi, It's looks really interesting, Can I give it a try?

**Comment by aryasoni98** [comment]
Hey !! I would like to work on it.

**Comment by huonggiangbui** [comment]
I am interested. Can I solve this @adavijit ?

**Comment by rajatmw1999** [comment]
Closed
