### ISSUE TITLE
Make API calls to youtube API

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#87]
Youtube provides API to fetch the data of particular courses based on a search query parameter.
Make Youtube API calls in the back end based on different search criterias like domain(web dev, data science), stack(mern mean, flutter etc), university and authors.
Fetch the JSON data and display it.

**Comment by BhuwanChandra** [comment]
@rajatmw1999 I would like to work on this issue. please assign this to me

**Comment by gpsuhas20** [comment]
@rajatmw1999  i wolud like to work on this please assign me this work.

**Comment by adityasanil** [comment]
I would like to work on this

**Comment by rajatmw1999** [comment]
Assgined to @adityasanil . Before working, go through the api error handling guidelines. You need to follow them. Deadline is 9th march
