### ISSUE TITLE
Make API calls to KhanAcademy API

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#88]
khanacademy.org provides API to fetch the data of particular courses based on a search query parameter.
Make khanacademy.org API calls in the back end based on different search criterias like domain(web dev, data science), stack(mern mean, flutter etc), university and authors.
Fetch the JSON data and display it.

**Comment by BhuwanChandra** [comment]
I would like to work on this. please assign me

**Comment by gpsuhas20** [comment]
i would like to work on this please assign me this.

**Comment by rajatmw1999** [comment]
Assigned to @gpsuhas20 . Before working, go through the api error handling guidelines. You need to follow them. Deadline is 9th march.

**Comment by rajatmw1999** [comment]
It looks like khan academy does not provide API for course comparison. I am closing this issue for now. You can checkout other unassigned issue and leave a comment there.
