### ISSUE TITLE
Make API calls to PluralSight API

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#89]
pluralsight.com provides API to fetch the data of particular courses based on a search query parameter.
Make pluralsight.com API calls in the back end based on different search criterias like domain(web dev, data science), stack(mern mean, flutter etc), university and authors.
Fetch the JSON data and display it.

**Comment by BhuwanChandra** [comment]
I would like to work on this. please assign me

**Comment by gpsuhas20** [comment]
@rajatmw1999  i would like to work on this please assign me this work.

**Comment by adityasanil** [comment]
Can I work on this issue?

**Comment by rajatmw1999** [comment]
Assigned to @BhuwanChandra . Before working, go through the api error handling guidelines. You need to follow them. Deadline is 9th march

**Comment by BhuwanChandra** [comment]
@rajatmw1999 I have looked at the Pluralsight API [documentation](https://www.pluralsight.com/product/professional-services/white-paper/api), they don't have the API for searching courses with specific search terms. however, they have an [API endpoint](http://api.pluralsight.com/api-v0.9/courses) that will give all the courses with some details in form of a .csv file.

**Comment by rajatmw1999** [comment]
WHat kind of courses will they give? Also, please attach the screenshot .csv response they are giving

**Comment by BhuwanChandra** [comment]
> WHat kind of courses will they give? Also, please attach the screenshot .csv response they are giving

courses that are currently available or previously available.

![courses](https://user-images.githubusercontent.com/46065877/76696715-5a19ad00-66b4-11ea-871f-de836a174e4c.JPG)

there are about 10000 courses entries in this .csv file

**Comment by rajatmw1999** [comment]
Okay, the data doesnot seem useful. Will have to close this isue
